export interface BlogPostMeta {
  slug: string;
  title: string;
  description: string;
  image: string;
  seoTitle?: string;
  metaDescription?: string;
  keywords?: string[];
  publishedAt?: string;
}

export const blogPosts: BlogPostMeta[] = [
  {
    slug: "balancing-work-family-and-islam-in-kampala",
    title: "Balancing Work, Family, and Islam in Kampala",
    description: "Learn practical ways to balance work, family, and Islam in Kampala while staying connected to the Quran in Luganda through audio, translation, and daily routines.",
    image: "/sc3.jpeg",
    seoTitle: "Balancing Work, Family, and Islam in Kampala | Luganda Quran Online",
    metaDescription: "Discover how Muslims in Kampala can balance work, family, and Islam with daily habits, Luganda Quran audio, and clear Luganda Quran translation online.",
    keywords: [
      "balancing work family and Islam in Kampala",
      "Luganda Quran Online",
      "Quran in Luganda",
      "Luganda Quran audio",
      "Luganda Quran translation",
      "Sheikh Ismail Sulaiman Nkata",
      "Islam in Kampala",
      "Muslim family life in Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "how-ugandan-youth-can-stay-connected-to-the-quran",
    title: "How Ugandan Youth Can Stay Connected to the Qur'an",
    description: "Discover practical ways Ugandan youth can stay connected to the Qur'an through Luganda Quran audio, clear translation, and consistent daily habits.",
    image: "/sc1.jpeg",
    seoTitle: "How Ugandan Youth Can Stay Connected to the Qur'an | Luganda Quran Online",
    metaDescription: "Learn how Ugandan youth can stay close to the Qur'an with Luganda Quran audio, Quran in Luganda translation, and realistic digital-age routines.",
    keywords: [
      "Ugandan youth and the Quran",
      "Luganda Quran Online",
      "Quran in Luganda",
      "Luganda Quran audio",
      "Quran translation in Luganda",
      "Sheikh Ismail Sulaiman Nkata",
      "Islamic youth in Uganda",
      "Muslim youth Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "how-to-stay-consistent-with-salah-in-a-busy-ugandan-lifestyle",
    title: "How to Stay Consistent with Salah in a Busy Ugandan Lifestyle",
    description: "Learn practical ways to stay consistent with Salah in Uganda by structuring your day around prayer and using Luganda Quran resources to deepen focus.",
    image: "/sc2.jpeg",
    seoTitle: "How to Stay Consistent with Salah in a Busy Ugandan Lifestyle | Luganda Quran Online",
    metaDescription: "Find practical ways to stay consistent with Salah in a busy Ugandan lifestyle using small routines, Quran in Luganda, and Luganda Quran audio.",
    keywords: [
      "consistent salah in Uganda",
      "busy Ugandan lifestyle and prayer",
      "Luganda Quran Online",
      "Quran in Luganda",
      "Luganda Quran audio",
      "Salah consistency tips",
      "Sheikh Ismail Sulaiman Nkata",
      "Muslim prayer habits Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "why-listening-to-quran-in-luganda-feels-more-personal",
    title: "Why Listening to Qur'an in Luganda Feels More Personal",
    description: "Discover why listening to the Qur'an in Luganda feels more personal for Ugandan Muslims through clearer understanding, emotional connection, and daily access.",
    image: "/sc3.jpeg",
    seoTitle: "Why Listening to Qur'an in Luganda Feels More Personal | Luganda Quran Online",
    metaDescription: "Learn why Quran in Luganda feels more personal through understanding, Luganda Quran audio, and clear translation that brings the message closer to daily life.",
    keywords: [
      "Quran in Luganda feels personal",
      "Luganda Quran Online",
      "Quran in Luganda",
      "Luganda Quran audio",
      "Quran translation in Luganda",
      "Sheikh Ismail Sulaiman Nkata",
      "Luganda Quran translation",
      "Ugandan Muslims and the Quran",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "why-young-ugandan-muslims-should-listen-to-the-quran-daily",
    title: "Why Young Ugandan Muslims Should Listen to the Qur'an Daily",
    description: "Learn why young Ugandan Muslims should listen to the Qur'an daily to stay grounded, build consistency, and grow through Luganda Quran audio and translation.",
    image: "/sc1.jpeg",
    seoTitle: "Why Young Ugandan Muslims Should Listen to the Qur'an Daily | Luganda Quran Online",
    metaDescription: "Discover why daily Luganda Quran audio helps young Ugandan Muslims stay connected to faith, build consistency, and understand the Qur'an more deeply.",
    keywords: [
      "young Ugandan Muslims and the Quran",
      "listen to the Quran daily",
      "Luganda Quran Online",
      "Luganda Quran audio",
      "Quran in Luganda",
      "Quran translation in Luganda",
      "Sheikh Ismail Sulaiman Nkata",
      "daily Quran listening Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "overcoming-stress-through-the-quran",
    title: "Overcoming Stress Through the Qur'an",
    description: "Discover how the Qur'an helps Muslims in Uganda manage stress through daily listening, Luganda Quran audio, and deeper understanding of its message.",
    image: "/sc2.jpeg",
    seoTitle: "Overcoming Stress Through the Qur'an | Luganda Quran Online",
    metaDescription: "Learn how Luganda Quran audio and Quran in Luganda translation can help relieve stress, calm the heart, and build steady spiritual resilience.",
    keywords: [
      "overcoming stress through the Quran",
      "Luganda Quran Online",
      "Luganda Quran audio",
      "Quran in Luganda",
      "Quran translation in Luganda",
      "stress relief in Islam",
      "Sheikh Ismail Sulaiman Nkata",
      "Muslim stress guidance Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "why-more-ugandans-are-turning-to-online-islamic-learning",
    title: "Why More Ugandans Are Turning to Online Islamic Learning",
    description: "Discover why more Ugandans are choosing online Islamic learning through mobile access, Luganda Quran resources, and flexible faith-based study.",
    image: "/sc3.jpeg",
    seoTitle: "Why More Ugandans Are Turning to Online Islamic Learning | Luganda Quran Online",
    metaDescription: "Learn why online Islamic learning is growing in Uganda through mobile access, Luganda Quran audio, trusted scholars, and flexible daily study.",
    keywords: [
      "online Islamic learning in Uganda",
      "Luganda Quran Online",
      "Luganda Quran audio",
      "Quran in Luganda",
      "Islamic learning Uganda",
      "Quran translation in Luganda",
      "Sheikh Ismail Sulaiman Nkata",
      "mobile Islamic learning Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "history-of-the-uganda-muslim-supreme-council-explained-simply",
    title: "History of the Uganda Muslim Supreme Council Explained Simply",
    description: "Learn the history of the Uganda Muslim Supreme Council, why it was formed, and how it continues to shape Muslim leadership and Islamic affairs in Uganda.",
    image: "/sc2.jpeg",
    seoTitle: "History of the Uganda Muslim Supreme Council Explained Simply | Luganda Quran Online",
    metaDescription: "Explore the history of the Uganda Muslim Supreme Council, its role in Muslim unity, and how Islamic learning in Uganda continues to grow today.",
    keywords: [
      "Uganda Muslim Supreme Council history",
      "UMSC Uganda explained",
      "Islam in Uganda history",
      "Luganda Quran Online",
      "Islamic leadership in Uganda",
      "Uganda National Mosque",
      "Muslim unity in Uganda",
      "Quran in Luganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "leadership-and-structure-of-umsc-how-it-works",
    title: "Leadership and Structure of UMSC: How It Works",
    description: "Understand the leadership and structure of the Uganda Muslim Supreme Council, from the Mufti to local mosques, and how the system supports Muslim coordination in Uganda.",
    image: "/sc1.jpeg",
    seoTitle: "Leadership and Structure of UMSC: How It Works | Luganda Quran Online",
    metaDescription: "Learn how the Uganda Muslim Supreme Council is structured, from the Mufti to mosque leadership, and how UMSC coordinates Muslim affairs across Uganda.",
    keywords: [
      "UMSC leadership structure",
      "Uganda Muslim Supreme Council leadership",
      "how UMSC works",
      "Mufti of Uganda role",
      "Majlis Al-Ulama Uganda",
      "Islamic leadership in Uganda",
      "Luganda Quran Online",
      "Muslim community structure Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "the-influence-of-kabaka-mutesa-i-on-islam-in-uganda",
    title: "The Influence of Kabaka Mutesa I on Islam in Uganda",
    description: "Learn how Kabaka Mutesa I shaped the early spread of Islam in Uganda through openness, court influence, and engagement with Muslim traders and teachers.",
    image: "/sc3.jpeg",
    seoTitle: "The Influence of Kabaka Mutesa I on Islam in Uganda | Luganda Quran Online",
    metaDescription: "Explore how Kabaka Mutesa I influenced the growth of Islam in Uganda and opened the way for deeper Islamic learning across Buganda and beyond.",
    keywords: [
      "Kabaka Mutesa I and Islam in Uganda",
      "Islam in Buganda history",
      "early Islam in Uganda",
      "Kabaka Mutesa I influence",
      "Luganda Quran Online",
      "Islamic history Uganda",
      "Quran in Luganda",
      "Muslim history in Buganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "why-the-quran-is-preserved-in-its-original-form",
    title: "Why the Qur'an Is Preserved in Its Original Form",
    description: "Learn why the Qur'an is preserved in its original form through memorization, written compilation, oral transmission, and continuous recitation across generations.",
    image: "/sc2.jpeg",
    seoTitle: "Why the Qur'an Is Preserved in Its Original Form | Luganda Quran Online",
    metaDescription: "Explore how the Qur'an has been preserved through memorization, written records, standardization, and living recitation traditions across the Muslim world.",
    keywords: [
      "why the Quran is preserved",
      "Quran preserved in original form",
      "oral transmission of the Quran",
      "Quran memorization history",
      "Luganda Quran Online",
      "Quran in Arabic and Luganda",
      "preservation of the Quran",
      "Quran recitation tradition",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "differences-between-recitation-tilawah-and-understanding-tafsir",
    title: "Differences Between Recitation (Tilawah) and Understanding (Tafsir)",
    description: "Understand the difference between Tilawah and Tafsir, and learn how recitation and explanation work together to deepen a Muslim's relationship with the Qur'an.",
    image: "/sc1.jpeg",
    seoTitle: "Differences Between Recitation (Tilawah) and Understanding (Tafsir) | Luganda Quran Online",
    metaDescription: "Learn the difference between Tilawah and Tafsir, and how Luganda Qur'an explanations help connect Arabic recitation with deeper understanding.",
    keywords: [
      "difference between Tilawah and Tafsir",
      "Tilawah and Tafsir explained",
      "Luganda Quran Online",
      "Quran in Luganda",
      "Luganda Quran audio",
      "Quran translation in Luganda",
      "Arabic recitation and meaning",
      "understanding the Quran in Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "islam-during-colonial-rule-in-uganda",
    title: "Islam During Colonial Rule in Uganda",
    description: "Explore how colonial rule reshaped Islam in Uganda through political change, missionary education, local resilience, and the gradual move toward stronger Muslim organization.",
    image: "/sc2.jpeg",
    seoTitle: "Islam During Colonial Rule in Uganda | Luganda Quran Online",
    metaDescription: "Learn how Islam in Uganda adapted during colonial rule through community resilience, trade networks, educational challenges, and evolving Islamic institutions.",
    keywords: [
      "Islam during colonial rule in Uganda",
      "colonial history of Islam in Uganda",
      "Muslims in colonial Uganda",
      "Islam in Buganda history",
      "Luganda Quran Online",
      "Islamic education in Uganda",
      "Uganda Muslim history",
      "Quran in Luganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "islam-in-the-buganda-kingdom-early-days-and-growth",
    title: "Islam in the Buganda Kingdom: Early Days and Growth",
    description: "Explore how Islam first spread in the Buganda Kingdom through trade, royal influence, community adoption, and gradual cultural interaction.",
    image: "/sc3.jpeg",
    seoTitle: "Islam in the Buganda Kingdom: Early Days and Growth | Luganda Quran Online",
    metaDescription: "Learn how Islam grew in the Buganda Kingdom through trade, Mutesa I's court, early Muslim communities, and the gradual spread of Islamic learning.",
    keywords: [
      "Islam in the Buganda Kingdom",
      "early Islam in Buganda",
      "Islam in Uganda history",
      "Mutesa I and Islam",
      "Luganda Quran Online",
      "Muslim history in Buganda",
      "Quran in Luganda",
      "early Muslim communities in Uganda",
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "authentic-luganda-quran-translation-by-sheikh-abdurazak-matovu",
    title: "The Authentic Luganda Quran Translation by Sheikh Abdurazak Matovu",
    description: "Discover the history and importance of the most authentic Luganda Quran text translation written by Sheikh Abdurazak Matovu. Read the Quran in Luganda today.",
    image: "/sc2.jpeg",
  },
  {
    slug: "how-to-download-full-luganda-quran-audio-by-sheikh-sulaiman-nkata",
    title: "How to Download Full Luganda Quran Audio by Sheikh Ismail Sulaiman Nkata",
    description: "Learn how to download the complete 114 surahs of the Quran in Luganda audio, translated by Sheikh Ismail Sulaiman Nkata. Listen online or offline anywhere in Uganda.",
    image: "/sc1.jpeg",
  },
  {
    slug: "listen-to-luganda-quran-online-guide",
    title: "Listen to Luganda Quran Online: Stay Connected Anywhere",
    description: "Looking for a way to listen to Luganda Quran audio online for free? Access full recitations by Sheikh Ismail Sulaiman Nkata on lugandaquran.online.",
    image: "/sc3.jpeg",
  },
];

export const blogPostsBySlug: Record<string, BlogPostMeta> = Object.fromEntries(
  blogPosts.map((post) => [post.slug, post])
);
